CREATE TABLE USERS(
 ID BIGINT AUTO_INCREMENT,
 EMAIL VARCHAR(30) NOT NULL,
 FIRSTNAME VARCHAR(30) NOT NULL,
 LASTNAME VARCHAR(30) NOT NULL,
 PHONE VARCHAR(15),
 PASSWORD VARCHAR(30) NOT NULL,
 PRIMARY KEY (ID)
);

ALTER TABLE USERS
  ADD CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL);

INSERT INTO users (EMAIL, FIRSTNAME, LASTNAME, PHONE, PASSWORD) VALUES ('kevser.bozoglu@gmail.com', 'kevser', 'bozoglu', '4159999999', 'TestClipper123');
INSERT INTO users (EMAIL, FIRSTNAME, LASTNAME, PHONE, PASSWORD) VALUES ('kevser.test@gmail.com', 'kevser', 'test', '4159999998', 'TestClipper123');

CREATE TABLE TEST_CASE_LOGIN(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  SUCCESS BOOL NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE TEST_CASE_LOGIN
  ADD CONSTRAINT test_case_login_user_id FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

INSERT INTO TEST_CASE_LOGIN (USER_ID, SUCCESS) VALUES ((SELECT u.id FROM users u WHERE u.email = 'kevser.bozoglu@gmail.com'), false);
INSERT INTO TEST_CASE_LOGIN (USER_ID, SUCCESS) VALUES ((SELECT u.id FROM users u WHERE u.email = 'kevser.test@gmail.com'), true);

CREATE TABLE TEST_RESULT_LOGIN(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 CASE_ID BIGINT NOT NULL,
 START_TIME TIMESTAMP NULL,
 END_TIME TIMESTAMP NULL,
 SUCCESS BOOL,
 PRIMARY KEY (ID)
);

ALTER TABLE TEST_RESULT_LOGIN
  ADD CONSTRAINT test_result_login_case_id FOREIGN KEY (CASE_ID) REFERENCES TEST_CASE_LOGIN (ID);